### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by ClassicSeniorBackup** [Rezanans-wow/Shoutcast-server-egg#1]
Shoutcast uses the port's 80 and 81, But i cant assign them these ports cause Pterodactyl uses 80 and 81 already, How do i change the ports?

**Comment by Rezanans-wow** [comment]
Hello, 

If me remember look var portbase_1=change_it to port allocated, also it has  portbase_2=change_it

**Comment by Rezanans-wow** [comment]
var portbase_1=change_it to port allocated, also it has portbase_2=change_it
